## Numpy Problems
[source](https://www.practiceprobs.com/problemsets/python-numpy/)

#### High School Reunion
[source](https://www.practiceprobs.com/problemsets/python-numpy/beginner/high-school-reunion/) With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday. Given these daily weights, build an array with your average weight per weekend.

In [4]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [8]:
## My Solution
sat = dailywts[5::7]
sun = dailywts[6::7]
ans = (sat + sun) / 2

## one liner
(dailywts[5::7] + dailywts[6::7]) / 2

array([183.9, 182.5, 181.1, 179.7, 178.3])

#### Gold Miner
[source](https://www.practiceprobs.com/problemsets/python-numpy/beginner/gold-miner/) After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [9]:
import numpy as np

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

print(gold)

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [17]:
## My Solution
ans = np.sum([gold[l1][l2] for [l1,l2] in locs])
ans

np.int64(20)